@baseUrl = http://localhost:3000/api

### Listar todos los libros -> 200
GET {{baseUrl}}/libros

### Filtrar libros disponibles -> 200
GET {{baseUrl}}/libros?disponible=true

### Ver detalle de un libro (trae autor y categorías) -> 200
GET {{baseUrl}}/libros/1

### Crear un libro -> 201
POST {{baseUrl}}/libros
Content-Type: application/json

{
  "titulo": "Rayuela",
  "precio": 7500,
  "imagen": "https://via.placeholder.com/150",
  "disponible": true,
  "autorId": 3
}

### Editar un libro completo -> 200
PUT {{baseUrl}}/libros/1
Content-Type: application/json

{
  "titulo": "El principito (Edición Especial)",
  "precio": 5200,
  "imagen": "https://via.placeholder.com/150",
  "disponible": true,
  "autorId": 1
}

### Eliminar un libro -> 204
DELETE {{baseUrl}}/libros/2




### Listar todos los autores -> 200
GET {{baseUrl}}/autores

### Ver un autor por ID -> 200
GET {{baseUrl}}/autores/1

### Crear un autor -> 201
POST {{baseUrl}}/autores
Content-Type: application/json

{
  "nombre": "Jorge Luis Borges",
  "nacionalidad": "Argentina"
}

### Editar un autor -> 200
PUT {{baseUrl}}/autores/1
Content-Type: application/json

{
  "nombre": "Antoine de Saint-Exupéry",
  "nacionalidad": "Francia"
}



### 400 - Body sin campo obligatorio (falta título)
POST {{baseUrl}}/libros
Content-Type: application/json

{
  "precio": 5000,
  "imagen": "https://via.placeholder.com/150",
  "autorId": 1
}

### 400 - ID inválido por parámetro
GET {{baseUrl}}/libros/abc

### 409 Conflict - Clave foránea inexistente
POST {{baseUrl}}/libros
Content-Type: application/json

{
  "titulo": "Libro Huérfano",
  "precio": 5000,
  "imagen": "https://via.placeholder.com/150",
  "autorId": 9999
}

### 409 Conflict - Autor duplicado por @unique
POST {{baseUrl}}/autores
Content-Type: application/json

{
  "nombre": "Antoine de Saint-Exupéry",
  "nacionalidad": "Francia"
}

### 409 Conflict - Borrar un autor que tiene libros asociados (Restrict / P2003)
DELETE {{baseUrl}}/autores/1

### 404 Not Found - Actualizar un recurso inexistente (P2025)
PUT {{baseUrl}}/libros/9999
Content-Type: application/json

{
  "titulo": "Libro Fantasma"
}